### ISSUE TITLE
Next steps as per our last discussion (Daniel)

### ISSUE THREAD

**Issue by svarvel** [svarvel/mobile-testbed#36]
1) verify that  sudo dumpsys telephony.registry > ".tel" from state-update.sh actually reports quality information for 5G as well   
2) investigate if manually switching to 5G is beneficial to explore more 5G functionalities. The run_zus()  function from net-testing.sh shows what I used to do for switching between 3G and 4G. Note also that in the new experiments we are not gonna run any "zus" related experiments afaik, aka we should disable that function (e.g., by putting it behind a flag)  
6) Improve location reporting. Integrate location reporting code from tag app inot Kenzo app, and consider disabling termux one as it seems less accurate update_location() in state-update.sh  
8) Start running the full system with a phone carried by Daniel and verify all the quirks related to data analysis -- (verify with Yasir) 
9) Verify YouTube solution works well
10) Verify behavior at phone startup. We needed an app to ensure termux boot and crontab would work as expected  
11) Investigate Bluetooth code in Kenzo app to monitor BT beacons. Either disable when net-testing.sh  is running or verify no interference 
14) Converge Kenzo and TAG mobile app into a single one

**Comment by DanielJang99** [comment]
1. When running `sudo dumpsys telephony.registry` under 5G connection, it indicates that the device is using LTE_CA (carrier aggregation) instead. I have only tested this on campus, so the output could be different in the wild. 
2.    Wrote a function that switches 5G <-> Lte in v2/net-testing. But 5G connection is not guaranteed.
3.  Termux location APIs have been replaced by location reports from the Kenzo app, which has merged the tag app 
4. To Do
5. Works fine mostly, but we should consider porting it to Kiwi browser - to be done later 
6. Done 
7. To Do 
8. Done
