### ISSUE TITLE
Next Steps for Daniel #2 

### ISSUE THREAD

**Issue by DanielJang99** [svarvel/mobile-testbed#40]
1. Fix missing values in reports from `web-test.sh` 
2. Fix DB relationship issue - perhaps use timestamp from each `state-update.sh` report as its primary key, which would be passed  to subsequent `net-testing.sh` to include as foreign key in their reports. Verify with Professor Yasir   
3. Compare termux location apis & `sudo dumpsys location` with kenzo location reports. Can we discard Google Maps if we are sticking with Kenzo location reports? 
4. Report current mobile connection (4G, 5G, etc), either through a script in crontab or Android APIs in Kenzo 
5. Verify google account authorization - can we trigger it? 
6. Verify whether net-test is enforced to run when there is new wifi connection 
7. Verify that the SmartTags script works when there are multiple SmartTags connected, and report to server (details to be discussed) 
8. Fix Youtube test issue - kill background activity 
9. Automatically append new device IMEI to `uid-list.txt` during initial setup

**Comment by DanielJang99** [comment]
@svarvel Is there anything I have missed in the list?

**Comment by svarvel** [comment]
10) verify Bluetooth passive collection: a) impact on other experiments, b) can we differentiate between airpods, airtags, phones, etc. 
11) speedtest needs to be bandwidth constrained
12) wehe integration: should run once a day on home wifi and on mobile network (on airalo too for devices on airalo). Need to be tested and verified data can easily be retrieved from mlab (nothing on the device) 
13) SIM1 vs SIM2 -- can we just physically block it? Small test when state-update runs? 
14) start collecting data and verify server and dashboard still works (and asses battery usage) 
15) clean the database (check with me later)
